index.html
index.js
package.json

Simple web app

---

dashboard.jsx
index.html

Retrieve branch list from github with simple ajax call.

---

README.md

codacy badge, resolves #18

---

README.md

remove Bitdeli badge

---

README.md

Details here:
https://github.com/igrigorik/ga-beacon

add GA Beacon for trackin

---

package.json

chore(package): update react to version 0.14.6

---

circle.yml
package.json

DB-114 checkout circle.ci

---

package.json

chore(package): update jsdom to version 9.2.0

---

package.json

chore(package): update react to version 15.1.0

---

.bithoundrc
.eslintrc.js
package.json

[bitHound](https://www.bithound.io/github/lowsky/dashboard) used jshint per default, which produces false positives.
Switching to [ESLint](http://eslint.org/) works much better.

Enable eslint in bitHound.

---

package.json

chore(package): update graphql to version 0.7.2

---

build.sh
swarm.json

DB-108: add basic giantswarm service config

---

package.json

chore(package): update jsdom to version 9.7.1

---

package.json

chore(package): update eslint-plugin-promise to version 3.2.1

---

package.json

chore(package): update jsdom to version 9.8.3

---

package.json

chore(package): update eslint-plugin-promise to version 3.3.1

---

package.json

chore(package): update eslint-plugin-react to version 6.7.0

---

package.json

Closes #261
https://greenkeeper.io/

chore(package): update graphql-relay to version 0.5.1

---

package.json

chore(package): update babel-plugin-transform-runtime to version 6.22.0

---

package.json

chore(package): update superagent to version 3.4.1

---

package.json

chore(package): update express to version 4.14.1

---

package.json

chore(package): update express-graphql to version 0.6.3

---

package.json

chore(package): update jsdom to version 9.12.0

---

package.json

chore(package): update babel-preset-react to version 6.24.1

---

package.json

Closes #308
https://greenkeeper.io/

chore(package): update jsdom to version 10.1.0

---

package.json

chore(package): update webpack-dev-server to version 2.4.5

---

package.json

chore(package): update enzyme to version 2.9.1

---

package.json

fix(package): update helmet to version 3.8.0

---

package.json

chore(package): update graphql to version 0.11.1

---

package.json
yarn.lock

chore(package): update relay-compiler to version 1.4.1

---

package.json

chore(package): update eslint-plugin-graphql to version 1.4.1

---

package.json

chore(package): update react-dom to version 16.1.1

---

package.json

chore(package): update enzyme to version 3.2.0

---

package.json
yarn.lock

chore(package): update graphql to version 0.12.3

---

package.json
yarn.lock

chore(package): update react-hot-loader to version 4.0.0-beta.14

---

.circleci/config.yml
.dockerignore
package.json
src/container/__tests__/.eslintrc

DB-511 optimise circle ci, add linting, split into more jobs

---

public/_redirects

add redirects config for netlify

---

src/components/Repo.js
src/components/User.js
src/components/__tests__/__snapshots__/Repo.test.js.snap
src/components/__tests__/__snapshots__/User.test.js.snap
src/container/__tests__/__snapshots__/UserRepo.test.js.snap
src/index/indexPage.js
src/restinpeace/restful.js
src/routes.js

fix NavBar menu + hamburger menu on Mobile

---

.circleci/config.yml
package.json
yarn.lock

note: needs CODACY_PROJECT_TOKEN env setup in circle ci

upload coverage to codecov service

---

.gitignore
.storybook/addons.js
.storybook/config.js
.storybook/webpack.config.js
package.json
src/__tests_/Storyshots.test.js
src/__tests_/__snapshots__/Storyshots.test.js.snap
src/container/BranchesTable.js
stories/index.stories.js
yarn.lock

Added some addons and functionality for snapshot testing, a11y, story sources and JSX source view

advanced storybook features

---

.eslintrc.js
src/__tests_/__snapshots__/Storyshots.test.js.snap
src/components/NavBar.js
src/container/__tests__/BranchInfoRow.test.js
stories/Intro.js

in dev mode, react-app showed some extra eslint warnings, which should also be reported in lint run.
We need to import default react eslint settings...

add lint config from standard react-app

---

src/relay/UserRepo.tsx
src/relay/__generated__/BranchInfoRow_branch.graphql.ts
src/relay/__generated__/BranchesTable_repo.graphql.ts
src/relay/__generated__/CommitWithStatuses_commit.graphql.ts
src/relay/__generated__/Repo_repo.graphql.ts
src/relay/__generated__/UserRepo_github.graphql.ts
src/relay/__generated__/User_user.graphql.ts
src/relay/__generated__/mainQuery.graphql.ts
src/relay/main.tsx
src/routes.tsx

DB-417: extract repo path info from route/url

---

yarn.lock

Use latest [Storybook 6 RC](https://github.com/storybookjs/storybook/issues/9311)
[Migration](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-53x-to-60x)

upgrade storybook

---

.github/workflows/chromatic.yml
package.json

https://github.com/chromaui/action

add chromatic workflow

---

lib/github.ts
lib/resolvers.ts
package.json
yarn.lock

Migrate to octokit

---

components/CommitWithStatuses.tsx
components/__tests__/removeExtraStatusesForSameContext.test.ts
components/removeExtraStatusesForSameContext.ts
pages/relay/[userName]/[repoName].tsx
pages/restful/[userName]/[repoName].tsx

* userName from url not properly extracted
* fix + add test for correct filtering the  commit's status list
* setting owner on rest page was missing for showing up in repo's path

Fix relay page and tiny issues

---

package.json
yarn.lock

Reverts lowsky/dashboard#1594 which introduces a compile error

Revert "Update dependency @types/react to v17.0.16"

---

components/CommitWithStatuses.story.js
components/Repo.story.js
components/User.story.js
container/BranchInfoRow.story.js
container/BranchesTable.story.js
container/UserRepo.story.js
pages/relay/[userName]/[repoName].tsx
stories/Pages.story.js
stories/__tests__/__snapshots__/Storyshots.test.ts.snap

improving things on storybook level:
* adding Args (introduced by Storybook 6)
* tried to circumvent blocking by missing routing in relay story, but still need to mock more ...
If all works correctly, there should not be any diff compared to reference snapshots (in chromatic) 👍

Add storybook args

---

components/CommitWithStatuses.tsx
components/NavBar.tsx
components/PullRequestInfo.tsx
components/Repo.tsx
components/Spinner.tsx
container/BranchInfoRow.tsx
package.json
stories/__tests__/__snapshots__/Storyshots.test.ts.snap
yarn.lock

Major font awesome

---

next.config.js

https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode

enable react strict mode

---

package.json
yarn.lock

This reverts commit d2cfdcea9ffc9c683f5ea93b2a93175f983cf6d0.

Revert "Update chakra-ui monorepo"

---

container/UserRepo.tsx
lib/relay.ts
lib/relayNetwork.ts
package.json
queries/__generated__/relayPageRepoQuery.graphql.ts
queries/relayPage.ts
yarn.lock

Actually adapting the fetch function in relay network to handle @defer'ed GraphQL queries.
See also meros library example:
https://github.com/maraisr/meros/blob/main/examples/relay-with-helix/app/relay.ts

Multipart fetch graphql supporting defer

---

cache/reactCache.tsx
components/CommitWithStatuses.tsx
components/PullRequestInfo.tsx
components/Repo.tsx
components/UILibContext.tsx
components/useUserRepoFromRoute.tsx
container/BranchInfoRow.tsx
container/BranchesTable.tsx
container/LazyUserRepo.tsx
container/NavBarWithRouting.tsx
container/UserRepo.tsx
package.json
pages/_app.tsx
pages/relay/[userName]/[repoName].tsx
pages/restful/[userName]/[repoName].tsx
pages/side-by-side/[userName]/[repoName].tsx
pages/wait-for-all/[userName]/[repoName].tsx
pages/waterfall/[userName]/[repoName].tsx
relay/BranchInfoRow.tsx
relay/BranchesTable.tsx
relay/CommitWithStatuses.tsx
relay/PullRequestInfo.tsx
relay/UserRepo.tsx
restinpeace/github.ts
stories/Pages.story.tsx
yarn.lock

* simplify: reduce prop-drilling by introducing a react context and hook for the route-based `userName`/`repoName`
* removing `doMergePR`
* adapt react-cache update
* intro useUserRepo hook

import latest improvement from react-meetup-suspense repo

---

.storybook/main.js
.storybook/preview.tsx

There is currently this PR 7678 on  https://github.com/chakra-ui/chakra-ui

Chakra-UI is currently not fully compatible with latest storybook

---

components/CommitWithStatuses.story.tsx
components/NavBar.story.tsx
components/PullRequestInfo.story.tsx
components/Repo.story.tsx
components/Spinner.story.tsx
components/User.story.tsx
container/BranchInfoRow.story.tsx
container/BranchesTable.story.tsx
container/UserRepo.story.tsx

Using the new format based on properly typed `args` on the stories 👍 based on the specific component's properties:
https://storybook.js.org/docs/7.0/react/writing-stories/args#story-args
migration description:
https://storybook.js.org/docs/7.0/react/writing-stories/args#story-args

upgrade storybook story format

---

app/layout.tsx
package.json
yarn.lock

interesting package / functionality, to show a progress indicator while NextJs page gets compiled and build.
works with app router

add top-loader progress bar

---

.storybook/main.ts
app/relay/[userName]/[repoName]/page.tsx
chromatic.config.json
package.json
yarn.lock

https://storybook.js.org/blog/visual-tests-addon-beta/

add chromatic-visual-tests addon

---

lib/types/resolvers.d.ts
queries/__generated__/relayPageRepoQuery.graphql.ts
queries/__generated__/relayPageUserQuery.graphql.ts
relay/__generated__/BranchInfoRow_branch.graphql.ts
relay/__generated__/BranchesTable_repo.graphql.ts
relay/__generated__/CommitWithStatuses_commit.graphql.ts
relay/__generated__/PullRequestInfo_pullRequest.graphql.ts
relay/__generated__/Repo_repo.graphql.ts
relay/__generated__/UserRepo_repo.graphql.ts
relay/__generated__/UserRepo_user.graphql.ts
relay/__generated__/User_user.graphql.ts

re-generated relay glue code

---

app/ChakraUIWrapper.tsx
app/ColorModeScriptClient.tsx
app/layout.tsx
components/DarkLightThemeToggle.tsx
components/NavBar.tsx

There is a problem in the mechanism to pick the light/dark color, picking
the dark-mode color when no theme was defined per-default.
This was leading to a mixture of dark color UI in the NavBar

fix-chakra-theme-issue
